name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Generate UI index
        run: npm run generate-ui-index

      - name: Build Next.js project
        run: npm run build

      # Si tu as des tests, décommente cette étape et adapte la commande
      # - name: Run tests
      #   run: npm test

      - name: Upload build artifacts (optional)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next
